// Generated by Cypress Author on 2026-05-07.

import {
  estadoJuego,
  jugador,
  objetivo,
  prepararApiJuego,
  solucion,
} from "../support/oodlegameApi";

function visitarConApi(options = {}) {
  prepararApiJuego(options);
  cy.visit("/");
}

function assertTableroVisible() {
  cy.contains(/TESTER CYPRESS.*NORMAL/i).should("be.visible");
  cy.contains("span", "Objetivo").should("be.visible");
  cy.get(`[aria-label="Validar intento. El resultado objetivo es ${objetivo}"]`).should(
    "be.disabled",
  );
}

describe("Ooodle E2E - estabilidad critica", () => {
  it("inicio disponible -> muestra formulario, reglas y ranking", () => {
    visitarConApi();

    cy.contains("h1", "Ooodle").should("be.visible");
    cy.contains("h2", "Iniciar partida").should("be.visible");
    cy.get('input[placeholder="Ej. Ada"]').should("be.visible").and("be.empty");
    cy.contains("button", "Normal").should("have.class", "chip_Dificultad--activa");
    cy.contains("Como jugar").should("be.visible");
    cy.contains("h2", "Ranking").should("be.visible");
    cy.contains(jugador).should("be.visible");
    cy.contains("350").should("be.visible");
  });

  it("ranking o estado inicial fallan -> la pantalla de inicio sigue usable", () => {
    visitarConApi({ rankingError: true });

    cy.contains("h2", "Iniciar partida").should("be.visible");
    cy.contains("Aun no hay puntajes").should("be.visible");
    cy.iniciarPartidaOoodle(jugador);

    assertTableroVisible();
    cy.get("@estadoApi").its("partidasIniciadas").should("deep.equal", [
      { nombre_Jugador: jugador, dificultad: "normal" },
    ]);
  });

  it("partida activa recuperada -> entra directo al tablero", () => {
    visitarConApi({
      estadoInicial: estadoJuego({ nombre_Jugador: jugador }),
    });

    assertTableroVisible();
    cy.contains("h2", "Iniciar partida").should("not.exist");
  });

  it("inicio rechazado por backend -> muestra error y no entra al tablero", () => {
    visitarConApi({ iniciarError: true });

    cy.iniciarPartidaOoodle(jugador);

    cy.contains("No se pudo iniciar la partida.").should("be.visible");
    cy.contains("h2", "Iniciar partida").should("be.visible");
    cy.contains("button", "Enviar ecuacion").should("not.exist");
  });

  it("nombre vacio -> muestra validacion del backend y permite corregir", () => {
    visitarConApi();

    cy.contains("button", "Iniciar juego").click();
    cy.wait("@iniciarJuego");
    cy.contains("Debes enviar un nombre de jugador valido.").should("be.visible");

    cy.iniciarPartidaOoodle(jugador, "dificil");

    cy.get("@estadoApi").its("partidasIniciadas").should("deep.equal", [
      { nombre_Jugador: jugador, dificultad: "dificil" },
    ]);
    cy.contains(/TESTER CYPRESS.*DIFICIL/i).should("be.visible");
    cy.contains("button", /^12$/).should("be.visible");
  });

  it("seleccion incompleta o duplicada -> no envia validacion", () => {
    visitarConApi();
    cy.iniciarPartidaOoodle(jugador);

    cy.seleccionarNumeros([1, 2, 3]);
    cy.contains("button", "Enviar ecuacion").should("be.disabled");
    cy.get("body").type("{enter}");
    cy.contains("Debes completar los cuatro espacios antes de validar.").should(
      "be.visible",
    );

    cy.contains("button", /^2$/).click();
    cy.get('[role="row"]')
      .first()
      .within(() => {
        cy.get('[aria-label="Posicion 1: 1, filled"]').should("be.visible");
        cy.get('[aria-label="Posicion 2: 3, filled"]').should("be.visible");
        cy.get('[aria-label="Posicion 3: vacia"]').should("be.visible");
      });
    cy.get("@estadoApi").its("operacionesValidadas").should("deep.equal", []);
  });

  it("seleccion de mas de cuatro numeros -> muestra error y no altera el intento", () => {
    visitarConApi();
    cy.iniciarPartidaOoodle(jugador);

    cy.seleccionarNumeros([1, 2, 3, 4]);
    cy.contains("button", /^5$/).click();

    cy.contains("Cada intento solo puede tener cuatro numeros.").should("be.visible");
    cy.get('[role="row"]')
      .first()
      .within(() => {
        cy.get('[aria-label="Posicion 1: 1, filled"]').should("be.visible");
        cy.get('[aria-label="Posicion 2: 2, filled"]').should("be.visible");
        cy.get('[aria-label="Posicion 3: 3, filled"]').should("be.visible");
        cy.get('[aria-label="Posicion 4: 4, filled"]').should("be.visible");
      });
    cy.get("@estadoApi").its("operacionesValidadas").should("deep.equal", []);
  });

  it("borrar y limpiar -> actualizan seleccion sin tocar backend", () => {
    visitarConApi();
    cy.iniciarPartidaOoodle(jugador);

    cy.seleccionarNumeros([1, 2]);
    cy.contains("button", "Borrar").click();
    cy.get('[role="row"]')
      .first()
      .within(() => {
        cy.get('[aria-label="Posicion 1: 1, filled"]').should("be.visible");
        cy.get('[aria-label="Posicion 2: vacia"]').should("be.visible");
      });

    cy.seleccionarNumeros([2, 3, 4]);
    cy.contains("button", "Limpiar").click();
    cy.get('[role="row"]')
      .first()
      .within(() => {
        cy.get('[aria-label="Posicion 1: vacia"]').should("be.visible");
        cy.get('[aria-label="Posicion 2: vacia"]').should("be.visible");
        cy.get('[aria-label="Posicion 3: vacia"]').should("be.visible");
        cy.get('[aria-label="Posicion 4: vacia"]').should("be.visible");
      });
    cy.get("@estadoApi").its("operacionesValidadas").should("deep.equal", []);
  });

  it("validacion rechazada por backend -> conserva tablero y muestra error", () => {
    visitarConApi({ validarError: true });
    cy.iniciarPartidaOoodle(jugador);

    cy.seleccionarNumeros([1, 2, 3, 4]);
    cy.contains("button", "Enviar ecuacion").click();
    cy.wait("@validarRespuesta");

    cy.contains("La operacion debe tener el formato numero+numero*numero-numero.").should(
      "be.visible",
    );
    cy.get('[role="dialog"]').should("not.exist");
    cy.get('[aria-label="Posicion 1: 1, filled"]').should("be.visible");
    cy.get("@estadoApi").its("operacionesValidadas").should("deep.equal", [
      "1+2*3-4",
    ]);
  });

  it("intento incorrecto -> registra retroalimentacion y reduce intentos", () => {
    visitarConApi();
    cy.iniciarPartidaOoodle(jugador);

    cy.seleccionarNumeros([1, 2, 3, 4]);
    cy.contains("button", "Enviar ecuacion").click();
    cy.wait("@validarRespuesta");

    cy.get('[aria-label="Posicion 1: 1, present"]').should("be.visible");
    cy.get('[aria-label="Posicion 2: 2, present"]').should("be.visible");
    cy.contains("Te quedan").parent().contains("5").should("be.visible");
    cy.get("@estadoApi").its("operacionesValidadas").should("deep.equal", [
      "1+2*3-4",
    ]);
  });

  it("victoria -> muestra resumen, ranking actualizado y no requiere guardado manual", () => {
    visitarConApi({
      ranking: [
        {
          nombre_jugador: jugador,
          puntaje: 350,
          intentos_usados: 2,
          estado: "acumulado",
          partidas_jugadas: 1,
          mejor_partida: 350,
        },
      ],
    });
    cy.iniciarPartidaOoodle(jugador);

    cy.seleccionarNumeros(solucion);
    cy.contains("button", "Enviar ecuacion").click();
    cy.wait("@validarRespuesta");

    cy.get('[role="dialog"]').should("be.visible");
    cy.contains("h2", "Ecuacion resuelta").should("be.visible");
    cy.contains(`2 + 3 \u00D7 4 - 1 = ${objetivo}`).should("be.visible");
    cy.contains("guardado y sumado").should("be.visible");
    cy.contains("Guardar puntaje").should("not.exist");
    cy.get("@estadoApi").its("scoreGuardado").should("equal", 0);
    cy.get("@estadoApi").its("rankingConsultado").should("be.greaterThan", 1);
  });

  it("derrota tras seis intentos -> muestra solucion y bloquea teclado", () => {
    visitarConApi({ forzarDerrota: true });
    cy.iniciarPartidaOoodle(jugador);

    for (let intento = 0; intento < 6; intento += 1) {
      cy.seleccionarNumeros([1, 2, 3, 4]);
      cy.contains("button", "Enviar ecuacion").click();
      cy.wait("@validarRespuesta");
    }

    cy.get('[role="dialog"]').should("be.visible");
    cy.contains("h2", "Se acabaron los intentos").should("be.visible");
    cy.contains(`2 + 3 \u00D7 4 - 1 = ${objetivo}`).should("be.visible");
    cy.contains("Resultado guardado automaticamente").should("be.visible");
    cy.contains("button", /^1$/).should("be.disabled");
  });

  it("navegacion y reinicio -> vuelven a estados jugables", () => {
    visitarConApi();
    cy.iniciarPartidaOoodle(jugador);

    cy.contains("button", "Inicio").click();
    cy.contains("h2", "Iniciar partida").should("be.visible");
    cy.contains("button", "Enviar ecuacion").should("not.exist");

    cy.iniciarPartidaOoodle(jugador);
    cy.contains("button", "Reiniciar").click();
    cy.wait("@iniciarJuego");

    cy.get("@estadoApi").its("partidasIniciadas").should("deep.equal", [
      { nombre_Jugador: jugador, dificultad: "normal" },
      { nombre_Jugador: jugador, dificultad: "normal" },
      { nombre_Jugador: jugador, dificultad: "normal" },
    ]);
    assertTableroVisible();
  });
});
